baseURL = "https://artyns-garden.vercel.app" # to be decided probably going to be Vercel
languageCode = "en-us"
title = "Artyn's digital garden"
metaDataFormat = "toml"

[taxonomies]
  tag = 'tags'

# [markup]
#   # This is the default from Hugo 0.60.0 onwards
#   defaultMarkdownHandler = "goldmark"

# [markup.highlight]
#   codeFences = true
#   noClasses = true
#   style = "perldoc"

[params]
  homeText = "Artyn's thoughts on technology. Themes: Emacs, Python, Lisp, NixOS, Linux, minimalistic and retrocomputing"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
[outputFormats.TOML]
mediaType = "application/toml"

[outputs]
  home = ["HTML"]



